stages:
- build
- test

painted:
  stage: build
  image: nixos/nix
  script: |
    nix-env -iA nixpkgs.nixUnstable
    nix-env -iA nixpkgs.git # we need this for the flake
    echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf
    nix build
    cp -Lr result out
  artifacts:
    paths:
    - out

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
